[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Raindrop_metalfoxdev"
version = "1.0"
authors = [
  { name="metalfoxdev"},
]
description = "Raindrop is a slick and intuitive, free and open source weather app for the linux terminal"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GPL v3 License",
    "Operating System :: Linux",
]

[project.urls]
"Homepage" = "https://github.com/metalfoxdev/Raindrop"
"Bug Tracker" = "https://github.com/metalfoxdev/Raindrop/issues"
